### PR TITLE
feat: allow skill to be installed via pip

### PR DESCRIPTION
**Pull request by mikejgray**

### CODE REVIEW

**Comment by burnsfisher** [comment]
Mike, what is with all the new stuff in .gitignore?  Files that get created now when you run tests?

**Comment by mikejgray** [comment]
> Mike, what is with all the new stuff in .gitignore? Files that get created now when you run tests?

I appended a generic Python gitignore that will ignore any files that get built by pip or other build systems, so those don't accidentally get committed. I can take it out if you'd like, but I figured it would help keep your repository tidy.

**Comment by burnsfisher** [comment]
No, that's fine.  I just wanted to understand.  Thanks again.

**Review by burnsfisher — APPROVED** [review]
Ok.  Thanks, Mike.

**Comment by burnsfisher** [comment]
BTW, does the "incompatible skills" part that you fixed have any effect that avoid having to manually change neon.yaml?

**Comment by mikejgray** [comment]
> BTW, does the "incompatible skills" part that you fixed have any effect that avoid having to manually change neon.yaml?

I'm hoping so, but I'm not exactly sure how well-supported that file is in Neon

**Pull request merged**
